# Generated by Django 5.1.1 on 2024-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_events_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_bookings',
            name='ticket_count',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
