# Generated by Django 5.1.1 on 2024-11-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_event_bookings_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_bookings',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfbooking',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
            preserve_default=False,
        ),
    ]
